name: 🐑 Update README Neofetch Stats

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Calculate dynamic data
        id: get_data
        run: |
          #!/bin/bash

          birthdate="2003-07-10"
          today=$(date +%Y-%m-%d)
          
          formatted_age=$(python3 -c "
          from datetime import date
          b = date(2003, 7, 10)
          t = date.today()
          delta = t - b
          
          days = delta.days
          
          y = t.year - b.year
          m = t.month - b.month
          d = t.day - b.day
          if d < 0:
              m -= 1
              from calendar import monthrange
              d += monthrange(t.year, t.month-1)[1]
          if m < 0:
              y -= 1
              m += 12
          print(f'{y} years, {m} months, {d} days')
          ")
          
          echo "age=$formatted_age" >> $GITHUB_OUTPUT


          repos=$(curl -s https://api.github.com/users/lenatran | jq '.public_repos')

          echo "age=$years" >> $GITHUB_OUTPUT
          echo "repos=$repos" >> $GITHUB_OUTPUT

      - name: Update README
        run: |
          sed -i "s/<!--AGE-->.*/<!--AGE-->${{ steps.get_data.outputs.age }}/" README.md
          sed -i "s/<!--REPOS-->.*/<!--REPOS-->${{ steps.get_data.outputs.repos }}/" README.md

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "🔁 update Neofetch stats" || echo "no changes to commit"
          git push
